"""Immutable catalog query API."""

from .catalog import normalize_name
from .filters import (
    AmbiguousNameError,
    AnnotationMatch,
    DimensionFilter,
    DistributionMatch,
    HistGermQueryError,
    InvalidIdentifierError,
    InvalidQueryError,
    PermissionReview,
    QueryFilter,
    ResourceMatch,
    SortSpec,
    UnknownIdentifierError,
    UnknownVocabularyValueError,
    UnsupportedSortError,
)
from .manifests import (
    CatalogQuery,
    ExternalReferenceError,
    ManifestEntry,
    ManifestExportOptions,
    ManifestSelection,
    ManifestSelectionError,
    ReviewRequiredError,
    TrainingDataManifest,
    manifest_json,
)

__all__ = [
    "AmbiguousNameError",
    "AnnotationMatch",
    "CatalogQuery",
    "DimensionFilter",
    "DistributionMatch",
    "ExternalReferenceError",
    "HistGermQueryError",
    "InvalidIdentifierError",
    "InvalidQueryError",
    "ManifestEntry",
    "ManifestExportOptions",
    "ManifestSelection",
    "ManifestSelectionError",
    "PermissionReview",
    "QueryFilter",
    "ResourceMatch",
    "ReviewRequiredError",
    "SortSpec",
    "UnknownIdentifierError",
    "UnknownVocabularyValueError",
    "UnsupportedSortError",
    "TrainingDataManifest",
    "manifest_json",
    "normalize_name",
]
