"""Deterministic generation and verification of the packaged inventory."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from importlib import metadata, resources
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from histgerm.loading import (
    HistGermLoadingError,
    discover_inventory_files,
    load_catalog,
)
from histgerm.models.catalog import Catalog
from histgerm.serialization import canonical_json_bytes
from histgerm.validation import CatalogDiagnostic, validate_catalog

SNAPSHOT_FORMAT_VERSION = 1
COMMAND_PROTOCOL = "histgerm.command.v1"
SNAPSHOT_NAME = "snapshot.json"
MANIFEST_NAME = "manifest.json"
GENERATED_FILES = frozenset({SNAPSHOT_NAME, MANIFEST_NAME})

_DRIVE_PATH = re.compile(r"^[A-Za-z]:[\\/]")
_POSIX_LOCAL_PATH = re.compile(r"^/(?:Users|home|var|tmp|etc|opt|mnt|Volumes)(?:/|$)")
_BASE64_BLOB = re.compile(r"^[A-Za-z0-9+/]{256,}={0,2}$")


class InventoryPackagingError(RuntimeError):
    """Base class for expected inventory packaging failures."""


class InventoryValidationError(InventoryPackagingError):
    """Authoring data cannot safely produce a package snapshot."""

    def __init__(self, diagnostics: Sequence[CatalogDiagnostic | str]) -> None:
        self.diagnostics = tuple(diagnostics)
        details = "\n".join(
            (
                f"{item.path}:{item.model_path}: {item.code}: {item.message}"
                if isinstance(item, CatalogDiagnostic)
                else str(item)
            )
            for item in self.diagnostics
        )
        super().__init__(f"authoring inventory validation failed:\n{details}")


class InventoryManifestError(InventoryPackagingError):
    """Generated snapshot metadata is malformed or inconsistent."""


@dataclass(frozen=True, slots=True)
class GeneratedInventory:
    """Canonical generated package files and their validated catalog."""

    catalog: Catalog
    snapshot: bytes
    manifest: bytes

    @property
    def files(self) -> dict[str, bytes]:
        return {MANIFEST_NAME: self.manifest, SNAPSHOT_NAME: self.snapshot}


@dataclass(frozen=True, slots=True)
class InventoryDrift:
    """Deterministically ordered differences from expected generated bytes."""

    changes: tuple[str, ...]

    @property
    def is_current(self) -> bool:
        return not self.changes


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _package_version() -> str:
    try:
        return metadata.version("histgerm")
    except metadata.PackageNotFoundError as error:
        raise InventoryPackagingError(
            "the histgerm distribution metadata is unavailable"
        ) from error


def _walk_source(root: Path) -> tuple[Path, ...]:
    if not root.is_dir():
        raise InventoryValidationError(
            [f"{root.as_posix()}: authoring inventory must be a directory"]
        )
    files: list[Path] = []
    pending = [root]
    while pending:
        directory = pending.pop()
        with os.scandir(directory) as entries:
            ordered = sorted(entries, key=lambda entry: entry.name, reverse=True)
        for entry in ordered:
            path = Path(entry.path)
            relative = path.relative_to(root).as_posix()
            if entry.is_symlink():
                raise InventoryValidationError(
                    [f"{relative}: symlinks are not permitted in authoring inventory"]
                )
            if entry.is_dir(follow_symlinks=False):
                pending.append(path)
            elif entry.is_file(follow_symlinks=False):
                if path.suffix.casefold() not in {".yaml", ".yml"}:
                    raise InventoryValidationError(
                        [f"{relative}: only authoring YAML files are permitted"]
                    )
                files.append(path)
            else:
                raise InventoryValidationError(
                    [f"{relative}: unsupported authoring filesystem entry"]
                )
    return tuple(sorted(files, key=lambda path: path.relative_to(root).as_posix()))


def _iter_json_values(value: Any, pointer: str = "") -> Sequence[tuple[str, Any]]:
    found: list[tuple[str, Any]] = [(pointer, value)]
    if isinstance(value, Mapping):
        for key in sorted(value):
            escaped = str(key).replace("~", "~0").replace("/", "~1")
            found.extend(_iter_json_values(value[key], f"{pointer}/{escaped}"))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            found.extend(_iter_json_values(child, f"{pointer}/{index}"))
    return found


def _validate_snapshot_payload(document: Mapping[str, Any]) -> None:
    failures: list[str] = []
    for pointer, value in _iter_json_values(document):
        if not isinstance(value, str):
            continue
        folded = value.casefold()
        if (
            folded.startswith(("file:", "data:"))
            or _DRIVE_PATH.match(value)
            or _POSIX_LOCAL_PATH.match(value)
            or value.startswith(("./", "../", ".\\", "..\\", "\\\\"))
        ):
            failures.append(
                f"{pointer or '/'}: local path or embedded data is forbidden"
            )
        elif _BASE64_BLOB.fullmatch(value):
            failures.append(f"{pointer or '/'}: base64-like payload is forbidden")
    if failures:
        raise InventoryValidationError(failures)


def _record_counts(catalog: Catalog) -> dict[str, int]:
    counts = {
        "publications": len(catalog.publications),
        "relationships": len(catalog.relationships),
        "resources": len(catalog.resources),
        "witnesses": len(catalog.witnesses),
        "works": len(catalog.works),
    }
    counts["total"] = sum(counts.values())
    return counts


def generate_inventory(source: Path) -> GeneratedInventory:
    """Validate authoring YAML and return canonical snapshot and manifest bytes."""

    source = source.resolve()
    authoring_files = _walk_source(source)
    discovered = discover_inventory_files(source)
    if authoring_files != discovered:
        raise InventoryValidationError(
            ["authoring file discovery did not cover the complete source tree"]
        )
    try:
        catalog, source_paths = load_catalog(source)
    except (HistGermLoadingError, OSError, ValidationError) as error:
        raise InventoryValidationError([str(error)]) from error
    report = validate_catalog(catalog, source_paths=source_paths)
    if not report.is_valid:
        raise InventoryValidationError(report.errors)

    document = catalog.model_dump(mode="json")
    _validate_snapshot_payload(document)
    snapshot = canonical_json_bytes(catalog)
    manifest_document = {
        "authoring_files": [
            {
                "path": path.relative_to(source).as_posix(),
                "sha256": _sha256(path.read_bytes()),
            }
            for path in authoring_files
        ],
        "generator_package_version": _package_version(),
        "inventory_release": str(catalog.inventory_release),
        "record_counts": _record_counts(catalog),
        "schema_version": str(catalog.schema_version),
        "snapshot_format_version": SNAPSHOT_FORMAT_VERSION,
        "snapshot_sha256": _sha256(snapshot),
    }
    manifest = canonical_json_bytes(manifest_document)
    verify_generated_inventory(snapshot, manifest)
    return GeneratedInventory(catalog=catalog, snapshot=snapshot, manifest=manifest)


def verify_generated_inventory(snapshot: bytes, manifest: bytes) -> Catalog:
    """Verify canonical generated bytes and return the validated snapshot catalog."""

    try:
        manifest_document = json.loads(manifest)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise InventoryManifestError(f"invalid manifest JSON: {error}") from error
    if not isinstance(manifest_document, dict):
        raise InventoryManifestError("manifest root must be a JSON object")
    if canonical_json_bytes(manifest_document) != manifest:
        raise InventoryManifestError("manifest bytes are not canonical JSON")
    required = {
        "authoring_files",
        "generator_package_version",
        "inventory_release",
        "record_counts",
        "schema_version",
        "snapshot_format_version",
        "snapshot_sha256",
    }
    if set(manifest_document) != required:
        raise InventoryManifestError("manifest fields do not match snapshot format 1")
    if manifest_document["snapshot_format_version"] != SNAPSHOT_FORMAT_VERSION:
        raise InventoryManifestError("unsupported snapshot format version")
    if manifest_document["snapshot_sha256"] != _sha256(snapshot):
        raise InventoryManifestError("snapshot SHA-256 does not match manifest")
    authoring_files = manifest_document["authoring_files"]
    if not isinstance(authoring_files, list) or authoring_files != sorted(
        authoring_files,
        key=lambda item: item.get("path", "") if isinstance(item, dict) else "",
    ):
        raise InventoryManifestError("manifest authoring files are not path-sorted")
    paths: list[str] = []
    for item in authoring_files:
        if not isinstance(item, dict) or set(item) != {"path", "sha256"}:
            raise InventoryManifestError("invalid authoring file manifest entry")
        path = item["path"]
        digest = item["sha256"]
        if (
            not isinstance(path, str)
            or not path
            or "\\" in path
            or path.startswith("/")
            or any(part in {"", ".", ".."} for part in path.split("/"))
        ):
            raise InventoryManifestError("invalid authoring file manifest path")
        if (
            not isinstance(digest, str)
            or len(digest) != 64
            or any(character not in "0123456789abcdef" for character in digest)
        ):
            raise InventoryManifestError("invalid authoring file SHA-256")
        paths.append(path)
    if len(paths) != len(set(paths)):
        raise InventoryManifestError("duplicate authoring file manifest path")
    if not isinstance(manifest_document["generator_package_version"], str):
        raise InventoryManifestError("invalid generator package version")
    try:
        catalog = Catalog.model_validate_json(snapshot)
    except ValidationError as error:
        raise InventoryManifestError(
            f"snapshot model validation failed: {error}"
        ) from error
    if canonical_json_bytes(catalog) != snapshot:
        raise InventoryManifestError("snapshot bytes are not canonical JSON")
    if manifest_document["schema_version"] != catalog.schema_version:
        raise InventoryManifestError("snapshot schema version does not match manifest")
    if manifest_document["inventory_release"] != catalog.inventory_release:
        raise InventoryManifestError(
            "snapshot inventory release does not match manifest"
        )
    if manifest_document["record_counts"] != _record_counts(catalog):
        raise InventoryManifestError("snapshot record counts do not match manifest")
    _validate_snapshot_payload(catalog.model_dump(mode="json"))
    return catalog


def build_inventory(source: Path, destination: Path) -> GeneratedInventory:
    """Replace the generated directory only after complete generation succeeds."""

    generated = generate_inventory(source)
    destination = destination.resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(
        tempfile.mkdtemp(prefix=f".{destination.name}-staging-", dir=destination.parent)
    )
    backup = destination.with_name(f".{destination.name}-backup-{os.getpid()}")
    try:
        for name, data in generated.files.items():
            (staging / name).write_bytes(data)
        verify_generated_directory(staging)
        if backup.exists():
            shutil.rmtree(backup)
        if destination.exists():
            os.replace(destination, backup)
        try:
            os.replace(staging, destination)
        except OSError:
            if backup.exists() and not destination.exists():
                os.replace(backup, destination)
            raise
        if backup.exists():
            shutil.rmtree(backup)
    finally:
        if staging.exists():
            shutil.rmtree(staging)
        if backup.exists() and destination.exists():
            shutil.rmtree(backup)
    return generated


def verify_generated_directory(directory: Path) -> Catalog:
    """Verify the complete generated file set and manifest."""

    if not directory.is_dir():
        raise InventoryManifestError(f"generated directory is missing: {directory}")
    actual = {
        path.relative_to(directory).as_posix()
        for path in directory.rglob("*")
        if path.is_file()
    }
    if actual != GENERATED_FILES:
        raise InventoryManifestError(
            f"generated file set mismatch: expected {sorted(GENERATED_FILES)}, "
            f"found {sorted(actual)}"
        )
    return verify_generated_inventory(
        (directory / SNAPSHOT_NAME).read_bytes(),
        (directory / MANIFEST_NAME).read_bytes(),
    )


def check_inventory(source: Path, destination: Path) -> InventoryDrift:
    """Compare validated source output with the complete bundled file set."""

    expected = generate_inventory(source).files
    actual: dict[str, bytes] = {}
    if destination.is_dir():
        actual = {
            path.relative_to(destination).as_posix(): path.read_bytes()
            for path in destination.rglob("*")
            if path.is_file()
        }
    changes = [
        *(f"missing:{name}" for name in sorted(expected.keys() - actual.keys())),
        *(f"extra:{name}" for name in sorted(actual.keys() - expected.keys())),
        *(
            f"changed:{name}"
            for name in sorted(expected.keys() & actual.keys())
            if expected[name] != actual[name]
        ),
    ]
    return InventoryDrift(changes=tuple(changes))


def load_verified_bundled_catalog(
    *,
    package: str = "histgerm.resources",
    resource: str = "inventory",
) -> Catalog:
    """Load bundled bytes after manifest, digest, and canonical-form verification."""

    parts = resource.split("/")
    if not parts or any(part in {"", ".", ".."} for part in parts):
        raise InventoryManifestError("package resource path escapes its boundary")
    directory = resources.files(package).joinpath(*parts)
    return verify_generated_inventory(
        directory.joinpath(SNAPSHOT_NAME).read_bytes(),
        directory.joinpath(MANIFEST_NAME).read_bytes(),
    )


def _envelope(
    command: str,
    status: str,
    *,
    errors: Sequence[Mapping[str, object]] = (),
    changes: Sequence[str] = (),
    result: Mapping[str, object] | None = None,
) -> dict[str, object]:
    return {
        "protocol": COMMAND_PROTOCOL,
        "command": command,
        "status": status,
        "errors": [dict(error) for error in errors],
        "warnings": [],
        "unresolved": [],
        "changes": list(changes),
        "result": dict(result or {}),
    }


def main(argv: Sequence[str] | None = None) -> int:
    """Run deterministic snapshot build and drift-check commands."""

    parser = argparse.ArgumentParser(prog="python -m histgerm.packaging")
    subparsers = parser.add_subparsers(dest="command", required=True)
    for name in ("build", "check"):
        command = subparsers.add_parser(name)
        command.add_argument("source")
        command.add_argument("destination")
        command.add_argument("--format", choices=("human", "json"), default="human")
    arguments = parser.parse_args(argv)
    command_name = f"packaging.{arguments.command}"
    output_format = str(arguments.format)
    try:
        if arguments.command == "build":
            generated = build_inventory(
                Path(str(arguments.source)), Path(str(arguments.destination))
            )
            changes: tuple[str, ...] = ()
            result = {
                "record_count": _record_counts(generated.catalog)["total"],
                "snapshot_sha256": _sha256(generated.snapshot),
            }
        else:
            drift = check_inventory(
                Path(str(arguments.source)), Path(str(arguments.destination))
            )
            changes = drift.changes
            result = {"current": drift.is_current}
            if not drift.is_current:
                if output_format == "json":
                    print(
                        json.dumps(
                            _envelope(
                                command_name,
                                "error",
                                changes=changes,
                                result=result,
                            ),
                            ensure_ascii=False,
                            sort_keys=True,
                            separators=(",", ":"),
                        )
                    )
                else:
                    print(
                        "packaged inventory is stale: " + ", ".join(changes),
                        file=sys.stderr,
                    )
                return 1
    except InventoryValidationError as error:
        diagnostic = {
            "code": "inventory_validation",
            "severity": "error",
            "path": str(arguments.source),
            "pointer": "",
            "message": str(error),
        }
        if output_format == "json":
            print(
                json.dumps(
                    _envelope(command_name, "error", errors=[diagnostic]),
                    ensure_ascii=False,
                    sort_keys=True,
                    separators=(",", ":"),
                )
            )
        else:
            print(error, file=sys.stderr)
        return 1
    except (OSError, InventoryPackagingError) as error:
        diagnostic = {
            "code": "input_error",
            "severity": "error",
            "path": str(arguments.source),
            "pointer": "",
            "message": str(error),
        }
        if output_format == "json":
            print(
                json.dumps(
                    _envelope(command_name, "error", errors=[diagnostic]),
                    ensure_ascii=False,
                    sort_keys=True,
                    separators=(",", ":"),
                )
            )
        else:
            print(error, file=sys.stderr)
        return 2
    if output_format == "json":
        print(
            json.dumps(
                _envelope(command_name, "ok", changes=changes, result=result),
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            )
        )
    else:
        action = "generated" if arguments.command == "build" else "is current"
        print(f"Packaged inventory {action}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "COMMAND_PROTOCOL",
    "GeneratedInventory",
    "InventoryDrift",
    "InventoryManifestError",
    "InventoryPackagingError",
    "InventoryValidationError",
    "SNAPSHOT_FORMAT_VERSION",
    "build_inventory",
    "check_inventory",
    "generate_inventory",
    "load_verified_bundled_catalog",
    "main",
    "verify_generated_directory",
    "verify_generated_inventory",
]
